### ISSUE TITLE
pygeostat unable to find executables

### ISSUE THREAD

**Issue by ericbdaniels** [CcgAlberta/pygeostat#1]
Hey all looks good, and thanks for including the open source GSLIB download in addition to the CCG member download.

It looks like executables are being downloaded correctly to my env/Lib/site-packages/pygeostat/executable directory, but getting an error about locating the program.  Maybe operator error?

Reproduce by:

```
import pygeostat as gs
gs.get_executable()
gs.Program("addcoord")
```

`Unable to find the provided program! Trying to use the executable pool shipped with pygeostat!`

Brand new env created using your environment.yml file,  and pip install pygeostat. Windows 10, python 3.6.10

Let me know if I can help

**Comment by MHadavand** [comment]
Hi, 
This is not error! It is a message to let the user know that the addcoord.exe included in pygeostat installation is being used instead of a user-provided executable. You should be able to keep using the program

add_coord = gs.Program("addcoord")
add_coord.run()

**Comment by ericbdaniels** [comment]
Ah, my bad. Thanks! I misinterpreted the messaging

**Comment by MHadavand** [comment]
No worries! I do appreciate reporting any potential issues. I will close this issues
