### ISSUE TITLE
Exception: ERROR calling: e:\anaconda\envs\python36\lib\site-packages\pygeostat\executable\varcalc. Check path to exe

### ISSUE THREAD

**Issue by cui-xiaoang96** [CcgAlberta/pygeostat#3]
Hi, I'm very interesting your outstanding project. It is important for to establish geological model.

But, I met a problem:

_Exception: ERROR calling: e:\anaconda\envs\python36\lib\site-packages\pygeostat\executable\varcalc. Check path to exe_
 
![图片](https://user-images.githubusercontent.com/41711907/89776197-fd73ce80-db3b-11ea-90ae-9c43afa59e9e.png)
When I run the In[45], the error appeared. The complete error is:
![图片](https://user-images.githubusercontent.com/41711907/89776313-37dd6b80-db3c-11ea-8694-16c7bc920fd7.png)

Could you give me some suggest to solve it, please?

And my work on "Win10".

**Comment by cui-xiaoang96** [comment]
I want to run your example code named "[_Boundary Modeling_](http://www.ccgalberta.com/pygeostat/examples.html#structural-modeling)"

**Comment by MHadavand** [comment]
Varcalc is one of the programs that is only provided for CCG members. If you/the company you work for is a CCG member, you can get and access token and download the CCG executable files using the get_executable function. Hope this helps.

**Comment by cui-xiaoang96** [comment]
I appreciate your help.

But I am not a member of CCG.

thanks again.
