### ISSUE TITLE
Slice_plot error

### ISSUE THREAD

**Issue by jvincent10** [CcgAlberta/pygeostat#4]
Encountered an error while trying to run the slice_plot function. Error message attached.
Running matplotlib version = 3.3.2

![image](https://user-images.githubusercontent.com/20852591/95491103-66b66900-0956-11eb-9c39-7a32390fb4b7.png)

**Comment by MHadavand** [comment]
This is an issue with matplotlib version and a specific isinstance check in pygeostat that uses a class from matplotlib that is deprecated at a specific version. This will be fixed in the next release of pygeostat.

**Comment by MHadavand** [comment]
The recent pull request merge addressed this issue. After package release, I will close this issue.

**Comment by MHadavand** [comment]
Fixed after release 1.0.7
