### ISSUE TITLE
Duplication of plot return from scatter_plots

### ISSUE THREAD

**Issue by jvincent10** [CcgAlberta/pygeostat#5]
Two sets of identical scatter plots are output from the gs.scatter_plots function
![scatter_plots_returns](https://user-images.githubusercontent.com/62772716/96176995-684dd700-0eea-11eb-8455-29553db27dbe.png)

**Comment by MHadavand** [comment]
This is because the scatter_plot function returns the fig object from matplotlib so the user can modify the plot
The solution is to get the return variable
_ = gs.scatter_plots()

**Comment by jvincent10** [comment]
Thank you for the clarification!
